create database customer_behavior;
use customer_behavior;

create table customer(
customer_id int,   
age int,   
gender varchar(10), 
item_purchased varchar(10),
category varchar(15),
purchase_amount_usd int,
location varchar(30), 
size varchar(10),  
color  varchar(10),
season varchar(30),
review_rating   float,
subscription_status varchar(20),
shipping_type  varchar(20),
discount_applied varchar(20),  
previous_purchases int,
payment_method   varchar(20),  
frequency_of_purchases  varchar(20),  
age_group varchar(20),
purchases_frequency_days int   
);
select * from customer;

-- --Q1. What is the total revenue generated by male vs. female customers?
select gender , sum(purchase_amount_usd) as Revenue 
from customer
group by gender
order by Revenue ;


-- --Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount_usd from customer
where discount_applied = "Yes" and purchase_amount_usd >= (select avg(purchase_amount_usd) from customer);


- -- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased   , round(avg(review_rating),2) as "Average Product Rating"
 from customer
 group by item_purchased
 order by avg(review_rating) desc
 limit 5;


-- --Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type , avg(purchase_amount_usd) as "Average Purchase Amount "from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- --Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- --between subscribers and non-subscribers.

select subscription_status, count(customer_id) as total_customer,
round(avg(purchase_amount_usd),2) as "Average Amount Spend" ,
round(sum(purchase_amount_usd),2) as Revenue  from customer
group by subscription_status
order by "Average Amount Spent", Revenue;
-- --Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased ,
round( 100.0 * sum(case when discount_applied = 'Yes' then 1 else 0 end ) / count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate;

-- --Q7. Segment customers into New, Returning, and Loyal based on their total 
-- -- number of previous purchases, and show the count of each segment. 

with customer_type as (
select customer_id , previous_purchases,
case
   when previous_purchases <= 1 then "New"
   when previous_purchases between 2 and 10 then "Returning"
   else "Loyal" end as customer_segment
from customer
)
select customer_segment , count(*) as "Number of Customer"
from customer_type
group by customer_segment;


-- --Q8. What are the top 3 most purchased products within each category? 
 with item_count as (
 select category , item_purchased, count(customer_id) as total_order,
 row_number() over(partition by category  order by count(customer_id) desc ) as item_rank
 from customer
 group by category,item_purchased
 )
 select item_rank,category , item_purchased , total_order
 from item_count
 where item_rank <=3;

 
-- --Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status , count(customer_id) as repeat_buyers
 from customer
 where previous_purchases > 5
 group by subscription_status;


-- --Q10. What is the revenue contribution of each age group? 
select age_group , sum(purchase_amount_usd) as revenue
 from customer
 group by age_group
 order by revenue desc;
































